services:
  app:
    build: .
    container_name: pumpfun_backend
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres.icphqjzppdblwgcbdrke:Jwjj90%40%40%2F%2F@aws-1-us-east-2.pooler.supabase.com:5432/postgres
    depends_on:
      - redis
    volumes:
      - .:/app:rw
      - /app/__pycache__
      - ./.env:/app/.env
    networks:
      - pumpfun_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: pumpfun_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - pumpfun_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:

networks:
  pumpfun_network:
    driver: bridge
